[global]
developmentMode = false

[server]
runOnSave = true
allowRunOnSave = true
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#667eea"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"